server:
  error:
    include-message: always
  servlet:
    context-path: /API_SERVER
  port: 1000
spring:
  profiles:
    active: uat
#  datasource:
#    url: jdbc:postgresql://localhost:5332/somuuat
#    username: somu
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
springdoc:
  swagger-ui:
    path: /somu-documentation
    try-it-out-enabled: true
    filter: true
  api-docs:
    path: /somu-api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

cors:
  allowed-origins: "*"
  allowed-methods: "*"

indian:
  railway:
    apikey: "c7e27cac7bmsh94f5195e115eb79p190b05jsne25693aaf370"
    host: "irctc1.p.rapidapi.com"